module.exports = {
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coveragePathIgnorePatterns: [
    '<rootDir>/@types/',
    '<rootDir>/core/',
    '<rootDir>/config/',
    '<rootDir>/modules/health/*.*',
    '<rootDir>/modules/*.*/controllers/',
    '<rootDir>/modules/*.*/repositories/',
    '<rootDir>/modules/*.*/constants/',
    '<rootDir>/modules/*.*/dtos/',
    '<rootDir>/modules/*.*/interfaces/',
    '<rootDir>/modules/*.*/tests/units/mocks/',
    '<rootDir>/modules/*.*/*.module.ts',
    '<rootDir>/modules/shared/*.*/',
    '<rootDir>/swagger/',
    '<rootDir>/app.module.ts',
    '<rootDir>/app.controller.ts',
    '<rootDir>/main-express.ts',
    '<rootDir>/main.ts',
  ],
  moduleNameMapper: {
    '^src/(.*)': '<rootDir>/../src/$1',
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  collectCoverage: false,
  coverageProvider: 'v8',
};